### ISSUE TITLE
OpenCV error

### ISSUE THREAD

**Issue by davine137** [dysonltd-zz/gts#1]
Hello, Mr. Akram Hussein

I'm Davine, worker in Vorwerk regarding GTS and IEC.

I already do all things like you said to Mr. Martin Weber, creating a new workbench with the newer version GTS 0.0.1 and 0.1.1. 

The problem now, after about 10 runs working on the same workbench, now the workbench failed to openCV wrong array.... (stated on the prompt display from GTS v 3.0.0.1)

so after tracking completed, pressing load on post process tab... after that pressing the process button, and suddenly the error notification pop up, and stop whole program. 

is it problem from the GTS or the computer? now i trying to make a new workbench again but still in progress.

and for the release tab on this blog, there are 0.1.2 and 0.1.3 but how can I use that? because I open it, and still in compiler mode or raw data (if I'm not mistaken).

and can I directly contact you with email for further guidance and information about some issue?

Best Regards,

Davine , Vorwerk GmbH in behalf of Mr. Martin Weber.

**Comment by akramhussein** [comment]
Hello Davine,

Thank you for your message. I have added a 0.1.4 release and installer (https://github.com/dysonltd/gts/releases/tag/v0.1.4) which has many fixes. Please download this and test this issue again. If you have any problems let me know.

We would prefer to keep all communication regarding the GTS here on Github.

Thanks,
Akram

**Comment by davine137** [comment]
Dear Mr. Akram,

I already try the new release, for some reason the openCV issue that I told you before are not solved. and the new release doesn't make red path while tracking the robot. and now although we already make a
room and save it, if we open the workbench again, it becomes unnamed room.

the issue of the tracking doesn't generate red path behind the robot already occurred in release 0.1.1 sometimes red path just dot continuously or doesn't have any red path behind. so the tracking post process become worse.

Is there any possibilities to solve both problem or new release again? because I'm personally still prefer using release 0.0.1. 

Is there any problem if I'm not install additional program? 

I attach a picture to show you. and please send your reply to davine@vorwerk.de

Best Regards,

Davine

---

 Dari: Akram Hussein notifications@github.com
Kepada: dysonltd/gts gts@noreply.github.com 
Cc: Davine davine_kohar@yahoo.co.id 
Dikirim: Rabu, 24 Juli 2013 12:47
Judul: Re: [gts] OpenCV error (#1)

Hello Davine,
Thank you for your message. I have added a 0.1.4 release and installer (https://github.com/dysonltd/gts/releases/tag/v0.1.4) which has many fixes. Please download this and test this issue again. If you have any problems let me know.
We would prefer to keep all communication regarding the GTS here on Github.
Thanks,
Akram

**Comment by akramhussein** [comment]
Hi Davine,

Do you have a copy of the 'gts.log' file that is created in the application folder? If you can send me this, I can analyse it to try and identify the problem.

I did not get a copy of the image.

0.1.1 unfortunately is broken and will not track correctly in some cases. We will shortly release 0.1.5 and would highly recommend upgrading to this.

Thanks,
Akram
