### ISSUE TITLE
Query related to one of the recent commit: d0a889b (Tracking improvements to track 100% automatically after the target is selected)

### ISSUE THREAD

**Issue by User-Neha** [dysonltd-zz/gts#13]
"Tracking improvements to track 100% automatically after the target is selected": Does this means that we need to mark the target on the GTS app window only once i.e for the first time in beginning and then tracking will happen on its own?
Previously, when the target used to go out of the recording video and come back again, then we had to mark the target's position manually on the GTS app window. I wanted to understand that after taking the latest code, will this be taken care off automatically i.e. no need to mark the target again manually when target gets lost and appears again on the recording view on GTS app window.

Thanks in advance.

**Comment by akramhussein** [comment]
Hi,

That is the intended purpose.

Thanks,
Akram

**Comment by User-Neha** [comment]
Hi Akram,

Thanks a ton for this update.

Best Regards,
Neha

**Comment by akramhussein** [comment]
Was actually done by Marc Barnada at iRobot.

**Comment by User-Neha** [comment]
Ok.. Thanks a lot Marc Barnada!

Best Regards,
Neha
